### ISSUE TITLE
ProgPoW algorithm connection failure &reset

### ISSUE THREAD

**Issue by ShallowRelease** [trexminer/T-Rex#1156]
Hello. I believe there’s to be an issue with this algorithm. While mining Sero coin the miner likes to time out and immediately reconnect to the pool. This happens in all pools so it’s not pool related imo. 
![1F09F6FF-F37D-4026-9973-F5772B6AFFF1](https://user-images.githubusercontent.com/101316629/157608259-2a76f12f-a309-468f-a472-6a2eafd2dedc.jpeg)

**Comment by ShallowRelease** [comment]
![87D51DFA-6E2E-4A37-BEB3-9C4BF697FEBF](https://user-images.githubusercontent.com/101316629/157611830-a5e707ff-b13c-4fe9-a717-bf57ebba84e1.jpeg)

doesn’t appear to have much of an effect on mining but I could be wrong.

**Comment by trollen28** [comment]
I have same problem with recconects t-rex-0.25.8 win10, tried -T 600 didnt help.

**Comment by trexminer** [comment]
Could you both please post the log files with `-T 600` set?

**Comment by trollen28** [comment]
![image](https://user-images.githubusercontent.com/84536055/157715692-3e3d53e6-94b5-4312-8166-28868a3d582e.png)

**Comment by trexminer** [comment]
Ok, thanks. It's probably a pool / networking issue then. You could try using another miner to confirm that.

**Comment by ShallowRelease** [comment]
Well no because it works with TTminer.

**Comment by trexminer** [comment]
No problem. We've looked into it further and identified the issue, it'll be fixed in the next release.

**Comment by ShallowRelease** [comment]
Thank you Sir

**Comment by rob4226** [comment]
Hi,
I'm using v0.25.9 mining SERO and am still getting a disconnect like every 30 seconds, same as with v0.25.8

```
20220318 23:53:53 WARN: Connection with pool gongpool.com:8008 timed out. Trying to reconnect...
20220318 23:53:53 Using protocol: stratum1.
20220318 23:53:53 Authorizing...
20220318 23:53:53 Authorized successfully.
20220318 23:53:53 progpow epoch: 247, block: 7416847, period: 148336, diff: 785.99 M

--------------------20220318 23:54:05 ---------------------
Mining at gongpool.com:8008 [13.57.114.181], diff: 785.99 M
GPU #0: Gigabyte RTX 3050 - 13.30 MH/s, [T:66C, P:99W, F:74%, E:134kH/W], 13/13 R:0%
Shares/min: 1.561 (Avg. 1.447)
Uptime: 9 mins 31 secs | Algo: progpow | T-Rex v0.25.9
WD: 9 mins 34 secs, shares: 13/13 

20220318 23:54:13 WARN: Connection with pool gongpool.com:8008 timed out. Trying to reconnect...
20220318 23:54:14 Using protocol: stratum1.
20220318 23:54:14 Authorizing...
20220318 23:54:14 Authorized successfully.
20220318 23:54:14 progpow epoch: 247, block: 7416847, period: 148336, diff: 785.99 M
20220318 23:54:20 [ OK ] 14/14 - 13.20 MH/s, 102ms ... GPU #0

--------------------20220318 23:54:36 ---------------------
Mining at gongpool.com:8008 [13.57.114.181], diff: 785.99 M
GPU #0: Gigabyte RTX 3050 - 13.26 MH/s, [T:66C, P:100W, F:74%, E:134kH/W], 14/14 R:0%
Shares/min: 1.536 (Avg. 1.436)
Uptime: 10 mins 1 sec | Algo: progpow | T-Rex v0.25.9
WD: 10 mins 4 secs, shares: 14/14 

20220318 23:54:36 progpow epoch: 247, block: 7416850, period: 148337, diff: 785.99 M
20220318 23:54:56 WARN: Connection with pool gongpool.com:8008 timed out. Trying to reconnect...
20220318 23:54:56 Using protocol: stratum1.
20220318 23:54:56 Authorizing...
20220318 23:54:56 Authorized successfully.
20220318 23:54:56 progpow epoch: 247, block: 7416850, period: 148337, diff: 785.99 M
```

**Comment by trexminer** [comment]
@rob4226 what parameters are you running t-rex with?

**Comment by trexminer** [comment]
The issue with sero.cash pool was that the miner would report its hashrate to the pool and the pool would reject it and drop the connection. The fix in 0.25.9 is to not report hashrate, I've tested it and it's working.
gongpool.com is a different story, it drops the connection intermittently for no apparent reason, I don't know why.

**Comment by ShallowRelease** [comment]
Gongpool is sketchy. I wouldn’t use it. From testing it seemed to me they horde rewards to themselves. Thank you for the fix trexminer. If someone wanted the code to use it manually for an earlier v. it was --no-hashrate-report .  Thank you for your diligence and the updates.

**Comment by rob4226** [comment]
Yeah screw Gongpool then, regardless of the connection issue, it doesn't look like I am getting the rewards I should. Gonna go back to CFX.
