### ISSUE TITLE
failed to stratum2-subscribe on stratum-ravencoin.flypool.org

### ISSUE THREAD

**Issue by jenishngl** [trexminer/T-Rex#128]
I am not able to use RVN miner. Am i doing something wrong? Can you please check

I have tried using both ports: 3333 & 13333 from https://ravencoin.flypool.org/start

I am using this in command prompt
`t-rex.exe -a kawpow -o stratum+tcp://stratum-ravencoin.flypool.org:13333 -u XXX.YYY`

Output:
```
20210107 09:12:49 T-Rex NVIDIA GPU miner v0.19.5  -  [CUDA v11.10 | Windows]
20210107 09:12:49 r.5f0b2f67355c
20210107 09:12:49
20210107 09:12:49 NVIDIA Driver v460.89
20210107 09:12:49 CUDA devices available: 1
20210107 09:12:49
20210107 09:12:49 WARN: DevFee 1% (kawpow)
20210107 09:12:49
20210107 09:12:49 URL : stratum+tcp://stratum-ravencoin.flypool.org:13333
20210107 09:12:49 USER: XXX.YYY
20210107 09:12:49 PASS:
20210107 09:12:49
20210107 09:12:49 Starting on: stratum-ravencoin.flypool.org:13333
20210107 09:12:49 Using protocol: stratum3.
20210107 09:12:49 ApiServer: HTTP server started on 0.0.0.0:4067
20210107 09:12:49 ------------------------------------------------------
20210107 09:12:49 For control navigate to: http://172.19.128.1:4067/trex
20210107 09:12:49 ------------------------------------------------------
20210107 09:12:49 ApiServer: Telnet server started on 0.0.0.0:4068
20210107 09:12:50 WARN: GPU #0(000100): Gigabyte GeForce RTX 2070 SUPER, intensity set to 20
20210107 09:12:59 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210107 09:12:59 WARN: failed to stratum2-subscribe on stratum-ravencoin.flypool.org:13333: can't parse json:
* Line 1, Column 1
  Syntax error: value, object or array expected.


20210107 09:12:59 ERROR: No connection, retry after 10 seconds
20210107 09:13:09 Using protocol: stratum3.
```

**Comment by MokraCota** [comment]
use port 3333 instead 13333

**Comment by trexminer** [comment]
Thanks MokraCota. 
@jenishngl Seems like it should be working fine, so check you connection details / wallet address. Otherwise it must be a networking issue.

**Comment by jenishngl** [comment]
> use port 3333 instead 13333
> 
> this works fine for me:
> `t-rex -a kawpow -o stratum+tcp://stratum-ravencoin.flypool.org:3333 -u Rxxxxxxxxxxxxxxxxxxxxxxxxxxxx.worker`

Just now i tested again with port 3333. Still getting the same error. Not sure what is the problem.

**Comment by jenishngl** [comment]
> Thanks MokraCota.
> @jenishngl Seems like it should be working fine, so check you connection details / wallet address. Otherwise it must be a networking issue.

I checked the wallet address as well. I generated the wallet address by the official Ravencoin Android app. Is there any way if that could be invalid?

**Comment by trexminer** [comment]
I just checked the connection from my side and it's working well. I think you need to set your password via `-p <password>`.

**Comment by arqtik** [comment]
Had the same issue. tried ssl port on flypool and works fine now.
`t-rex.exe -a kawpow -o stratum+ssl://stratum-ravencoin.flypool.org:3443 -u Rxxxxxxxxxxxxxxxxxxxxxxxxxxx -p x`

**Comment by mattboya** [comment]
I'm having the same problem and using the ssl port did not work.

Are there certain ports that need to be opened up on your router?

**Comment by ZenFree01** [comment]
I have this issue as well.  I'm not sure why but if I go to Norton - settings - firewall - Intrusion Detection and turn off Intrusion protection then it will connect (for me).  I can then almost immediately turn it back on and I don't get the issue again until it restarts.

I have can't explain why, it's just how I get it to work.  I've tried to disable a number of the Signatures but not sure which one is blocking it (in the +configure section).

**Comment by RoosterPax** [comment]
@jenishngl 
Hey I had this exact same problem with my system however I have an Asus router. I went into my router settings, into AiProtection and then turned off Two-Way IPS. After this my miner worked fine with no issues. Just wondering maybe yourself has an Asus router. I saw someone else had the same issue on a reddit page with an Asus router.

**Comment by jenishngl** [comment]
@RoosterPax  - Indeed, I have an Asus router as well. Thanks for this info. But i fixed this issue by changing `stratum+tcp://stratum-ravencoin.flypool.org:13333` to `stratum+tcp://stratum-ravencoin.flypool.org:3443` in the miner URL config

**Comment by mattboya** [comment]
@RoosterPax - I have an Asus router too, so I will definitely try this out, thanks for the tip!

**Comment by MichaelArcher** [comment]
Confirmed, it is an ASUS AiProtection issue.  For me, the SSL fix worked.  I figured it had to be a network issue, because at work I can run it just fine on my laptop.

It's probably because a lot of apps have been building in miners as a kind of malware.  My ASUS wouldn't even let the miner that Razer has built in to their software package run.

**Comment by TheFrostyboss** [comment]
I got this error when one of my GPUs was <5.0 capable, but I fixed it by specifying the proper device numbers. Automatically ignoring old devices (with an appropriate warning) would be helpful.

**Comment by Ori2846** [comment]
> @RoosterPax - Indeed, I have an Asus router as well. Thanks for this info. But i fixed this issue by changing tls `stratum+tcp://stratum-ravencoin.flypool.org:13333` to ssl `stratum+ssl://stratum-ravencoin.flypool.org:3443` in the miner URL config

This worked for me thanks

**Comment by technopremium** [comment]
Worked changing the ssl stratum+tcp://stratum-ravencoin.flypool.org:13333 to ssl stratum+ssl://stratum-ravencoin.flypool.org:3443 for me. 

Thanks for sharing

**Comment by chris-malin** [comment]
If you encounter this issue while dual mining (e.g. ETH-ALPH), make sure you have the correct dual_algo selected (e.g. blake3 for ALPH).

**Comment by DonCarnage47** [comment]
> @jenishngl Hey I had this exact same problem with my system however I have an Asus router. I went into my router settings, into AiProtection and then turned off Two-Way IPS. After this my miner worked fine with no issues. Just wondering maybe yourself has an Asus router. I saw someone else had the same issue on a reddit page with an Asus router.

This was the exact issue I had , thanks
